version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - lesliecdubs
  assignees:
  - lesliecdubs
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: stylelint-declaration-strict-value
    versions:
    - 1.7.10
    - 1.7.7
    - 1.7.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: uglify-js
    versions:
    - 3.12.5
    - 3.12.6
    - 3.12.7
    - 3.12.8
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: "@11ty/eleventy-plugin-syntaxhighlight"
    versions:
    - 3.0.6
